INSERT INTO public.bingo_cards (description, public) VALUES ('Attend an AoC event at work.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Solve a problem after day 10.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Solve a task before 8 am.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Use test driven development to solve a task.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Refactor code from and earlier day.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Finish 15 days.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Share an AoC meme with a co-worker.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Solve a problem using pair programming.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Receive help from a co-worker.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Recruit a co-worker to AoC.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Finish 10 days.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Finish 5 days.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Create GitHub repository for your solutions.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Help a co-worker with a problem.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Discuss a solution during lunch break.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Use the same help-function on two different problems.', true);
