INSERT INTO public.bingo_cards (description, public) VALUES ('Attend an AoC event at work.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Solve a problem after day 10.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Solve a task before 8 am.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Use test driven development to solve a task.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Refactor code from and earlier day.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Finish 15 days.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Share an AoC meme with a co-worker.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Solve a problem using pair programming.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Receive help from a co-worker.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Recruit a co-worker to AoC.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Finish 10 days.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Finish 5 days.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Create GitHub repository for your solutions.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Help a co-worker with a problem.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Discuss a solution during lunch break.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Use the same help-function on two different problems.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Your code works correctly on the sample input but not the actual input.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('You submit a wrong answer that turns out to be 1 off from the true answer.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Your back-of-the envelope math shows your naive solution will take several months to compute the answer.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('You abuse a language feature to cheese a puzzle that''s intended to be hard.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('You realize the puzzle is much easier to solve by hand than with code.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Ask for help on r/adventofcode.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Post a solution to the megathread.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Make the global leaderboard.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Top a private leaderboard.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Refer back to a solution from previous years.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Edit the input instead of doing complex parsing.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Accidentally submit the solution for an example.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Use only single-letter variables in your code.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Resort to a constraint solver.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('Use eval to decode a string or evaluate an expression.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('All your variables are named after one of the Yule Lads.', true);
INSERT INTO public.bingo_cards (description, public) VALUES ('You have a solution that does not work correctly with the sample input, but does work with the actual input.', true);
