// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Jakob Maležič",
            "url": "https://github.com/Blarc"
        },
        "license": {
            "name": "GNU General Public License v3.0",
            "url": "https://www.gnu.org/licenses/gpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bingoCards": {
            "get": {
                "description": "Get all bingo cards.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bingo Card"
                ],
                "summary": "Get all bingo cards.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.BingoCardDto"
                            }
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "Get information about the user that is currently logged in.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user information.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserDto"
                        }
                    }
                }
            }
        },
        "/me/bingoBoard": {
            "post": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "Create a new bingo board.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bingo Board"
                ],
                "summary": "Create bingo board.",
                "parameters": [
                    {
                        "description": "Bingo Board Name",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateBingoBoardDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserDto"
                        }
                    }
                }
            }
        },
        "/me/bingoBoard/{id}": {
            "delete": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "Delete a bingo board.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bingo Board"
                ],
                "summary": "Delete bingo board.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bingo Board ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserDto"
                        }
                    }
                }
            }
        },
        "/me/bingoCard/{id}": {
            "post": {
                "security": [
                    {
                        "Token": []
                    }
                ],
                "description": "Add or remove bingo card from user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Click bingo card.",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Bingo Card ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.CreateBingoBoardDto": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "models.BingoBoardDto": {
            "type": "object",
            "properties": {
                "bingo_cards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BingoCardDto"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.BingoCardDto": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "selected": {
                    "type": "boolean"
                },
                "user_count": {
                    "type": "integer"
                }
            }
        },
        "models.UserDto": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "bingo_boards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BingoBoardDto"
                    }
                },
                "bingo_cards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BingoCardDto"
                    }
                },
                "github_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "reddit_url": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Token": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Advent of Code Bingo API",
	Description:      "Advent of Code Bingo API in Go using Gin framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
