basePath: /api/v1
definitions:
  controllers.CreateBingoCardDto:
    properties:
      description:
        type: string
    required:
    - description
    type: object
  models.BingoBoardDto:
    properties:
      bingo_cards:
        items:
          $ref: '#/definitions/models.BingoCardDto'
        type: array
      name:
        type: string
      short_uuid:
        type: string
    type: object
  models.BingoCardDto:
    properties:
      description:
        type: string
      id:
        type: string
      selected:
        type: boolean
      user_count:
        type: integer
    type: object
  models.BingoCardId:
    properties:
      id:
        type: string
    required:
    - id
    type: object
  models.UserDto:
    properties:
      avatar_url:
        type: string
      bingo_boards:
        items:
          $ref: '#/definitions/models.BingoBoardDto'
        type: array
      bingo_cards:
        items:
          $ref: '#/definitions/models.BingoCardDto'
        type: array
      github_url:
        type: string
      name:
        type: string
      personal_bingo_board:
        $ref: '#/definitions/models.BingoBoardDto'
      reddit_url:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Jakob Maležič
    url: https://github.com/Blarc
  description: Advent of Code Bingo API in Go using Gin framework.
  license:
    name: GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html
  title: Advent of Code Bingo API
  version: "1.0"
paths:
  /bingoBoard:
    post:
      consumes:
      - application/json
      description: Create a new bingo board with random bingo cards.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserDto'
      security:
      - Token: []
      summary: Create bingo board.
      tags:
      - Bingo Board
  /bingoBoard/{id}:
    delete:
      consumes:
      - application/json
      description: Irrevocably delete a bingo board.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserDto'
      security:
      - Token: []
      summary: Delete bingo board.
      tags:
      - Bingo Board
    get:
      consumes:
      - application/json
      description: Get a bingo board.
      parameters:
      - description: Bingo Board ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - Token: []
      summary: Get bingo board.
      tags:
      - Bingo Board
  /bingoBoard/{id}/addBingoCard:
    put:
      consumes:
      - application/json
      description: Add a bingo card to a bingo board.
      parameters:
      - description: Bingo Board ID
        in: path
        name: id
        required: true
        type: string
      - description: Bingo Card UUID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.BingoCardId'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - Token: []
      summary: Add bingo card.
      tags:
      - Bingo Board
  /bingoBoard/{id}/join:
    post:
      consumes:
      - application/json
      description: Join a bingo board.
      parameters:
      - description: Bingo Board ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - Token: []
      summary: Join bingo board.
      tags:
      - Bingo Board
  /bingoBoard/{id}/leave:
    delete:
      consumes:
      - application/json
      description: Leave a bingo board.
      parameters:
      - description: Bingo Board ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - Token: []
      summary: Leave bingo board.
      tags:
      - Bingo Board
  /bingoBoard/{id}/removeBingoCard:
    put:
      consumes:
      - application/json
      description: Remove a bingo card from a bingo board.
      parameters:
      - description: Bingo Board ID
        in: path
        name: id
        required: true
        type: string
      - description: Bingo Card UUID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.BingoCardId'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - Token: []
      summary: Remove bingo card.
      tags:
      - Bingo Board
  /bingoCards:
    get:
      consumes:
      - application/json
      description: Get all bingo cards.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.BingoCardDto'
            type: array
      summary: Get all bingo cards.
      tags:
      - Bingo Card
    post:
      consumes:
      - application/json
      description: Create a bingo card.
      parameters:
      - description: Bingo Card
        in: body
        name: bingoCard
        required: true
        schema:
          $ref: '#/definitions/controllers.CreateBingoCardDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BingoCardDto'
      summary: Create a bingo card.
      tags:
      - Bingo Card
  /me:
    get:
      consumes:
      - application/json
      description: Get information about the user that is currently logged in.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserDto'
      security:
      - Token: []
      summary: Get user information.
      tags:
      - User
  /me/bingoCard/{id}:
    post:
      consumes:
      - application/json
      description: Add or remove bingo card from user.
      parameters:
      - description: Bingo Card ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserDto'
      security:
      - Token: []
      summary: Click bingo card.
      tags:
      - User
securityDefinitions:
  Token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
